export ZSH="$HOME/.oh-my-zsh"

# Load external plugins that must come after Oh My Zsh
source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Default browser fallback for web-search
export BROWSER=${BROWSER:-firefox}

ZSH_THEME="jonathan"

plugins=(
  #Built-in
  git
  z
  sudo
  history-substring-search
  web-search
  pip
  colored-man-pages


  #External plugins
  zsh-autosuggestions 
  zsh-syntax-highlighting
  autoenv
)
source ~/dotfiles/zsh/aliases.zsh
source $ZSH/oh-my-zsh.sh
