# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

export ZSH="$HOME/.oh-my-zsh"

# Load external plugins that must come after Oh My Zsh
source ~/dotfiles/zsh/ohmyzsh-custom/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source ~/dotfiles/zsh/ohmyzsh-custom/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

# Default browser fallback for web-search
export BROWSER=${BROWSER:-firefox}

ZSH_CUSTOM="$HOME/dotfiles/zsh/ohmyzsh-custom"
ZSH_THEME="powerlevel10k/powerlevel10k"

plugins=(
  #Built-in
  git
  z
  sudo
  history-substring-search
  web-search
  pip
  colored-man-pages


  #External plugins
  zsh-autosuggestions 
  zsh-syntax-highlighting
  autoenv
)
source ~/dotfiles/zsh/aliases.zsh
source $ZSH/oh-my-zsh.sh

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
